const ASSET_BASE="https://raw.githubusercontent.com/EthanM32122/Bazaar-Pack21/main/artifacts/api-server/public/content";
function blookImg(n){return ASSET_BASE+"/blooks/"+encodeURIComponent(n)+".webp"}
function packImg(n){return ASSET_BASE+"/packs/"+encodeURIComponent(n)+".webp"}
const CATALOG={
startTokens:1500,claimAmount:4000,
rarities:{"Common":{color:"#ffffff",exp:0},"Uncommon":{color:"#29e629",exp:5},"Rare":{color:"#0000ff",exp:10},"Epic":{color:"#8000ff",exp:25},"Legendary":{color:"#ffaf0f",exp:100},"Chroma":{color:"#00ccff",exp:1000},"Mystical":{color:"#843af2",exp:2500}},
packs:[
{name:"Medieval",price:25,color1:"#d9b36c",color2:"#4a2c12",blooks:["Elf","Fairy","Slime Monster","Witch","Wizard","Dragon","Jester","Queen","Unicorn","King","Phantom King"],img:packImg("Medieval")},
{name:"Fast Food",price:25,color1:"#ff6b3d",color2:"#8a1c1c",blooks:["Fries","Tater Tot","Ice Cream","Cheese Wedge","Vanilla Donut","Pizza","Glow in the Dark Pizza"],img:packImg("Fast Food")},
{name:"Breakfast",price:25,color1:"#ffcf5c",color2:"#8a4a12",blooks:["Breakfast Combo","Cereal","Milk","Orange Juice","Toast","Yogurt","Pancakes","Waffle","French Toast","Chocolate Milk","Bacon and Eggs","Rainbow Waffles"],img:packImg("Breakfast")},
{name:"Space",price:25,color1:"#8a7fff",color2:"#12103a",blooks:["Earth","Alien","Meteor","Stars","Planet","UFO","Spaceship","Astronaut","Rainbow Astronaut"],img:packImg("Space")},
{name:"Spooky",price:25,color1:"#b45cff",color2:"#3a1052",blooks:["Frankenstein","Pumpkin","Swamp Monster","Vampire","Caramel Apple","Mummy","Zombie","Werewolf","Ghost","Spooky Ghost"],img:packImg("Spooky")},
{name:"Aquatic",price:25,color1:"#5fc9ff",color2:"#0b3a6a",blooks:["Old Boot","Clownfish","Crab","Frog","Jellyfish","Blobfish","Octopus","Pufferfish","Narwhal","Dolphin","Baby Shark","Megalodon","Golden Blobfish"],img:packImg("Aquatic")},
{name:"Bot",price:25,color1:"#b0b8c4",color2:"#2e3440",blooks:["Angry Bot","Happy Bot","Lil Bot","Lovely Bot","Buddy Bot","Watson","Brainy Bot","Mega Bot"],img:packImg("Bot")},
{name:"Dino",price:25,color1:"#a8d977",color2:"#2f5d2a",blooks:["Amber","Dino Egg","Dino Fossil","Stegosaurus","Brontosaurus","Velociraptor","Triceratops","Tyrannosaurus Rex"],img:packImg("Dino")}
],
blooks:[
{name:"Elf",rarity:"Uncommon",chance:13.395,pack:"Medieval",img:blookImg("Elf")},{name:"Fairy",rarity:"Uncommon",chance:13.4,pack:"Medieval",img:blookImg("Fairy")},{name:"Slime Monster",rarity:"Uncommon",chance:13.4,pack:"Medieval",img:blookImg("Slime Monster")},{name:"Witch",rarity:"Uncommon",chance:13.4,pack:"Medieval",img:blookImg("Witch")},{name:"Wizard",rarity:"Uncommon",chance:13.4,pack:"Medieval",img:blookImg("Wizard")},{name:"Dragon",rarity:"Rare",chance:9,pack:"Medieval",img:blookImg("Dragon")},{name:"Jester",rarity:"Rare",chance:9,pack:"Medieval",img:blookImg("Jester")},{name:"Queen",rarity:"Rare",chance:9,pack:"Medieval",img:blookImg("Queen")},{name:"Unicorn",rarity:"Epic",chance:5,pack:"Medieval",img:blookImg("Unicorn")},{name:"King",rarity:"Legendary",chance:1,pack:"Medieval",img:blookImg("King")},{name:"Phantom King",rarity:"Mystical",chance:0.005,pack:"Medieval",img:blookImg("Phantom King")},
{name:"Fries",rarity:"Uncommon",chance:37,pack:"Fast Food",img:blookImg("Fries")},{name:"Tater Tot",rarity:"Uncommon",chance:37,pack:"Fast Food",img:blookImg("Tater Tot")},{name:"Ice Cream",rarity:"Rare",chance:11,pack:"Fast Food",img:blookImg("Ice Cream")},{name:"Cheese Wedge",rarity:"Rare",chance:11,pack:"Fast Food",img:blookImg("Cheese Wedge")},{name:"Vanilla Donut",rarity:"Epic",chance:3.2,pack:"Fast Food",img:blookImg("Vanilla Donut")},{name:"Pizza",rarity:"Legendary",chance:0.75,pack:"Fast Food",img:blookImg("Pizza")},{name:"Glow in the Dark Pizza",rarity:"Chroma",chance:0.05,pack:"Fast Food",img:blookImg("Glow in the Dark Pizza")},
{name:"Earth",rarity:"Uncommon",chance:18.676,pack:"Space",img:blookImg("Earth")},{name:"Alien",rarity:"Uncommon",chance:18.673,pack:"Space",img:blookImg("Alien")},{name:"Meteor",rarity:"Uncommon",chance:18.683,pack:"Space",img:blookImg("Meteor")},{name:"Stars",rarity:"Uncommon",chance:18.678,pack:"Space",img:blookImg("Stars")},{name:"Planet",rarity:"Rare",chance:9.962,pack:"Space",img:blookImg("Planet")},{name:"UFO",rarity:"Rare",chance:9.962,pack:"Space",img:blookImg("UFO")},{name:"Spaceship",rarity:"Epic",chance:4.483,pack:"Space",img:blookImg("Spaceship")},{name:"Astronaut",rarity:"Legendary",chance:0.448,pack:"Space",img:blookImg("Astronaut")},{name:"Rainbow Astronaut",rarity:"Mystical",chance:0.005,pack:"Space",img:blookImg("Rainbow Astronaut")},
{name:"Frankenstein",rarity:"Uncommon",chance:18.486,pack:"Spooky",img:blookImg("Frankenstein")},{name:"Pumpkin",rarity:"Uncommon",chance:18.484,pack:"Spooky",img:blookImg("Pumpkin")},{name:"Swamp Monster",rarity:"Uncommon",chance:18.484,pack:"Spooky",img:blookImg("Swamp Monster")},{name:"Vampire",rarity:"Uncommon",chance:18.484,pack:"Spooky",img:blookImg("Vampire")},{name:"Caramel Apple",rarity:"Rare",chance:6.694,pack:"Spooky",img:blookImg("Caramel Apple")},{name:"Mummy",rarity:"Rare",chance:6.694,pack:"Spooky",img:blookImg("Mummy")},{name:"Zombie",rarity:"Rare",chance:6.694,pack:"Spooky",img:blookImg("Zombie")},{name:"Werewolf",rarity:"Epic",chance:5.196,pack:"Spooky",img:blookImg("Werewolf")},{name:"Ghost",rarity:"Legendary",chance:0.649,pack:"Spooky",img:blookImg("Ghost")},{name:"Spooky Ghost",rarity:"Mystical",chance:0.005,pack:"Spooky",img:blookImg("Spooky Ghost")},
{name:"Old Boot",rarity:"Uncommon",chance:14.514,pack:"Aquatic",img:blookImg("Old Boot")},{name:"Clownfish",rarity:"Uncommon",chance:14.563,pack:"Aquatic",img:blookImg("Clownfish")},{name:"Crab",rarity:"Uncommon",chance:14.563,pack:"Aquatic",img:blookImg("Crab")},{name:"Frog",rarity:"Uncommon",chance:14.563,pack:"Aquatic",img:blookImg("Frog")},{name:"Jellyfish",rarity:"Uncommon",chance:14.563,pack:"Aquatic",img:blookImg("Jellyfish")},{name:"Blobfish",rarity:"Rare",chance:6.602,pack:"Aquatic",img:blookImg("Blobfish")},{name:"Octopus",rarity:"Rare",chance:6.602,pack:"Aquatic",img:blookImg("Octopus")},{name:"Pufferfish",rarity:"Rare",chance:6.602,pack:"Aquatic",img:blookImg("Pufferfish")},{name:"Narwhal",rarity:"Epic",chance:3.786,pack:"Aquatic",img:blookImg("Narwhal")},{name:"Dolphin",rarity:"Epic",chance:2.913,pack:"Aquatic",img:blookImg("Dolphin")},{name:"Baby Shark",rarity:"Legendary",chance:0.485,pack:"Aquatic",img:blookImg("Baby Shark")},{name:"Megalodon",rarity:"Legendary",chance:0.194,pack:"Aquatic",img:blookImg("Megalodon")},{name:"Golden Blobfish",rarity:"Chroma",chance:0.05,pack:"Aquatic",img:blookImg("Golden Blobfish")},
{name:"Angry Bot",rarity:"Uncommon",chance:19.5,pack:"Bot",img:blookImg("Angry Bot")},{name:"Happy Bot",rarity:"Uncommon",chance:19.5,pack:"Bot",img:blookImg("Happy Bot")},{name:"Lil Bot",rarity:"Uncommon",chance:19.5,pack:"Bot",img:blookImg("Lil Bot")},{name:"Lovely Bot",rarity:"Uncommon",chance:19.5,pack:"Bot",img:blookImg("Lovely Bot")},{name:"Buddy Bot",rarity:"Rare",chance:9,pack:"Bot",img:blookImg("Buddy Bot")},{name:"Watson",rarity:"Rare",chance:9,pack:"Bot",img:blookImg("Watson")},{name:"Brainy Bot",rarity:"Epic",chance:3.7,pack:"Bot",img:blookImg("Brainy Bot")},{name:"Mega Bot",rarity:"Legendary",chance:0.3,pack:"Bot",img:blookImg("Mega Bot")},
{name:"Amber",rarity:"Uncommon",chance:19.5,pack:"Dino",img:blookImg("Amber")},{name:"Dino Egg",rarity:"Uncommon",chance:19.5,pack:"Dino",img:blookImg("Dino Egg")},{name:"Dino Fossil",rarity:"Uncommon",chance:19.5,pack:"Dino",img:blookImg("Dino Fossil")},{name:"Stegosaurus",rarity:"Uncommon",chance:19.5,pack:"Dino",img:blookImg("Stegosaurus")},{name:"Brontosaurus",rarity:"Rare",chance:9,pack:"Dino",img:blookImg("Brontosaurus")},{name:"Velociraptor",rarity:"Rare",chance:9,pack:"Dino",img:blookImg("Velociraptor")},{name:"Triceratops",rarity:"Epic",chance:3.7,pack:"Dino",img:blookImg("Triceratops")},{name:"Tyrannosaurus Rex",rarity:"Legendary",chance:0.3,pack:"Dino",img:blookImg("Tyrannosaurus Rex")},
{name:"Breakfast Combo",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Breakfast Combo")},{name:"Cereal",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Cereal")},{name:"Milk",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Milk")},{name:"Orange Juice",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Orange Juice")},{name:"Toast",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Toast")},{name:"Yogurt",rarity:"Uncommon",chance:12.579,pack:"Breakfast",img:blookImg("Yogurt")},{name:"Pancakes",rarity:"Rare",chance:9.184,pack:"Breakfast",img:blookImg("Pancakes")},{name:"Waffle",rarity:"Rare",chance:9.184,pack:"Breakfast",img:blookImg("Waffle")},{name:"French Toast",rarity:"Epic",chance:5.102,pack:"Breakfast",img:blookImg("French Toast")},{name:"Chocolate Milk",rarity:"Legendary",chance:1,pack:"Breakfast",img:blookImg("Chocolate Milk")},{name:"Bacon and Eggs",rarity:"Chroma",chance:0.05,pack:"Breakfast",img:blookImg("Bacon and Eggs")},{name:"Rainbow Waffles",rarity:"Mystical",chance:0.005,pack:"Breakfast",img:blookImg("Rainbow Waffles")}
]
};
