const BLOOKS = CATALOG.blooks;
const PACKS = CATALOG.packs.filter(p => p.name !== 'Miscellaneous');
const RARITIES = CATALOG.rarities;
const blookByName = Object.fromEntries(BLOOKS.map(b => [b.name, b]));
const NAV = [['stats','S','Stats'],['mine','M','Mine'],['market','K','Market'],['blooks','B','My Blooks'],['bazaar','Z','Bazaar'],['craft','C','Craft'],['trade','T','Trade'],['clans','G','Clans'],['friends','F','Friends'],['chat','H','Chat'],['leaderboard','L','Leaderboard'],['gifts','P','Gifts'],['settings','O','Settings'],['admin','A','Admin']];
function safeGet(k,f){try{return localStorage.getItem(k)||f}catch(e){return f}}
function safeSet(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}
function getUsers(){try{return JSON.parse(safeGet('ck_users','{}'))}catch(e){return{}}}
function currentUser(){return safeGet('ck_current','')}
function defaultData(){return{tokens:CATALOG.startTokens,exp:0,packsOpened:0,mined:0,role:'player',inventory:{},friends:[],clan:'',lastMine:0,lastClaim:0}}
function getData(u){try{return Object.assign(defaultData(),JSON.parse(safeGet('ck_data_'+u,'{}')))}catch(e){return defaultData()}}
function saveData(u,d){safeSet('ck_data_'+u,JSON.stringify(d))}
function getGlobal(k,f){try{return JSON.parse(safeGet('ck_g_'+k,JSON.stringify(f)))}catch(e){return f}}
function setGlobal(k,v){safeSet('ck_g_'+k,JSON.stringify(v))}
function levelForExp(exp){return Math.floor(Math.sqrt(exp/100))+1}
function rollPack(packName,luckMultiplier=1){
  const pack=PACKS.find(p=>p.name===packName);if(!pack)return null;
  const entries=pack.blooks.map(n=>blookByName[n]).filter(b=>b&&b.chance>0);if(!entries.length)return null;
  const total=entries.reduce((s,b)=>s+b.chance,0);
  const rollOnce=()=>{let roll=Math.random()*total;for(const b of entries){roll-=b.chance;if(roll<=0)return b}return entries[entries.length-1]};
  if(packName==='Top')return Math.random()*100<0.5?(blookByName['1k']||null):null;
  let winner=rollOnce();let extra=Math.max(0,luckMultiplier-1);
  while(extra>0){if(Math.random()<Math.min(1,extra)){const c=rollOnce();if(c.chance<winner.chance)winner=c}extra-=1}
  return winner;
}
function openModal(t){closeModals();document.getElementById(t+'Modal').classList.add('active')}
function closeModals(){['loginModal','registerModal'].forEach(id=>document.getElementById(id).classList.remove('active'))}
function switchModal(t){closeModals();openModal(t)}
function doRegister(){
  const u=document.getElementById('regUser').value.trim(),p=document.getElementById('regPass').value,p2=document.getElementById('regPass2').value,err=document.getElementById('regError');
  err.style.color='#f87171';err.textContent='';
  if(!u||!p){err.textContent='Fill all fields';return}
  if(!/^[a-zA-Z0-9_-]{3,20}$/.test(u)){err.textContent='Username 3-20 letters/numbers/_/-';return}
  if(p!==p2){err.textContent='Passwords do not match';return}
  if(p.length<3){err.textContent='Password min 3';return}
  const users=getUsers();if(users[u]){err.textContent='Username taken';return}
  users[u]=p;safeSet('ck_users',JSON.stringify(users));safeSet('ck_last',u);
  const d=defaultData();if(Object.keys(users).length===1){d.role='owner';d.tokens=10000}
  saveData(u,d);
  document.getElementById('loginUser').value=u;document.getElementById('loginPass').value='';
  closeModals();openModal('login');
  const le=document.getElementById('loginError');le.style.color='#4ade80';le.textContent='Account created! Login.';
}
function doLogin(){
  const u=document.getElementById('loginUser').value.trim(),p=document.getElementById('loginPass').value,err=document.getElementById('loginError');
  err.style.color='#f87171';err.textContent='';
  const users=getUsers();if(!users[u]||users[u]!==p){err.textContent='Invalid login';return}
  safeSet('ck_current',u);safeSet('ck_last',u);afterLogin(u);
}
function afterLogin(u){closeModals();document.getElementById('landing').style.display='none';document.getElementById('app').classList.add('active');buildNav();refreshUI();showPage('stats')}
function logout(){try{localStorage.removeItem('ck_current')}catch(e){}location.reload()}
window.addEventListener('DOMContentLoaded',()=>{try{const last=localStorage.getItem('ck_last');if(last)document.getElementById('loginUser').value=last;const cur=localStorage.getItem('ck_current');if(cur)afterLogin(cur)}catch(e){}buildRarityTabs()});
function buildNav(){const nav=document.getElementById('nav');nav.innerHTML='';const role=getData(currentUser()).role;NAV.forEach(([page,ico,label])=>{if(page==='admin'&&!['mod','admin','coowner','owner'].includes(role))return;const b=document.createElement('button');b.className='nav-item';b.dataset.page=page;b.innerHTML='<span class="ico">'+ico+'</span>'+label;b.onclick=()=>showPage(page);nav.appendChild(b)})}
function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.nav-item[data-page]').forEach(n=>n.classList.remove('active'));const panel=document.getElementById('page-'+page);if(panel)panel.classList.add('active');const nav=document.querySelector('.nav-item[data-page="'+page+'"]');if(nav)nav.classList.add('active');refreshUI()}
function refreshUI(){const u=currentUser();if(!u)return;const d=getData(u);document.getElementById('chipUser').textContent=u;document.getElementById('chipTokens').textContent=d.tokens.toLocaleString();const count=Object.values(d.inventory).reduce((a,b)=>a+b,0);document.getElementById('chipBlooks').textContent=count;document.getElementById('chipLevel').textContent=levelForExp(d.exp);renderStats();renderMarket();renderBlooks();renderBazaar();renderCraft();renderTrade();renderClans();renderFriends();renderChat();renderLB();renderGifts();fillSelects()}
function renderStats(){const d=getData(currentUser());const count=Object.values(d.inventory).reduce((a,b)=>a+b,0);document.getElementById('statsGrid').innerHTML='<div class="blook-card"><div class="bn text-rainbow" style="font-size:1.6rem">'+d.tokens.toLocaleString()+'</div><div class="br">Tokens</div></div><div class="blook-card"><div class="bn text-rainbow" style="font-size:1.6rem">'+count+'</div><div class="br">Blooks</div></div><div class="blook-card"><div class="bn text-rainbow" style="font-size:1.6rem">'+d.packsOpened+'</div><div class="br">Packs opened</div></div><div class="blook-card"><div class="bn text-rainbow" style="font-size:1.6rem">'+levelForExp(d.exp)+'</div><div class="br">Level</div></div><div class="blook-card"><div class="bn text-rainbow" style="font-size:1.6rem">'+d.mined+'</div><div class="br">Mines</div></div><div class="blook-card"><div class="bn text-rainbow" style="font-size:1.2rem">'+d.role+'</div><div class="br">Role</div></div>'}
function renderMarket(){const g=document.getElementById('marketGrid');g.innerHTML='';PACKS.forEach(p=>{const el=document.createElement('div');el.className='pack-card';el.style.background='linear-gradient(160deg,'+p.color1+','+p.color2+')';el.innerHTML='<img src="'+p.img+'" alt="'+p.name+'" loading="lazy" onerror="this.style.opacity=.3"><div class="pname">'+p.name+'</div><div class="pprice">'+p.price+' tokens</div><button class="btn sm">Open</button>';el.querySelector('button').onclick=(e)=>{e.stopPropagation();openPack(p.name)};el.onclick=()=>openPack(p.name);g.appendChild(el)})}
function openPack(name){const pack=PACKS.find(p=>p.name===name);if(!pack)return;const u=currentUser();const d=getData(u);if(d.tokens<pack.price){alert('Not enough tokens');return}d.tokens-=pack.price;const got=rollPack(name);if(!got){saveData(u,d);refreshUI();document.getElementById('openImg').style.display='none';document.getElementById('openName').textContent='Nothing...';document.getElementById('openRarity').textContent='Better luck next time';document.getElementById('openRarity').style.color='#9ca3af';document.getElementById('openModal').classList.add('active');return}d.packsOpened++;d.inventory[got.name]=(d.inventory[got.name]||0)+1;d.exp+=(RARITIES[got.rarity]?.exp||0);saveData(u,d);document.getElementById('openImg').style.display='';document.getElementById('openImg').src=got.img;document.getElementById('openName').textContent=got.name;const col=RARITIES[got.rarity]?.color||'#fff';document.getElementById('openRarity').textContent=got.rarity+(got.chance?' · '+got.chance+'%':'');document.getElementById('openRarity').style.color=col==='rainbow'?'#ec4899':col;document.getElementById('openModal').classList.add('active');refreshUI()}
let blookFilter='all';
function buildRarityTabs(){const tabs=document.getElementById('rarityTabs');const rs=['all',...Object.keys(RARITIES)];tabs.innerHTML=rs.map(r=>'<button class="tab '+(r==='all'?'on':'')+'" onclick="filterBlooks(\''+r+'\',this)">'+r+'</button>').join('')}
function filterBlooks(f,btn){blookFilter=f;document.querySelectorAll('#rarityTabs .tab').forEach(t=>t.classList.remove('on'));btn.classList.add('on');renderBlooks()}
function renderBlooks(){const d=getData(currentUser());const g=document.getElementById('blooksGrid');g.innerHTML='';const names=Object.keys(d.inventory).filter(n=>d.inventory[n]>0).sort();if(!names.length){g.innerHTML='<p class="muted">Open packs in Market to collect blooks.</p>';return}names.forEach(n=>{const b=blookByName[n];if(!b)return;if(blookFilter!=='all'&&b.rarity!==blookFilter)return;const col=RARITIES[b.rarity]?.color||'#fff';const el=document.createElement('div');el.className='blook-card';el.style.borderColor=col==='rainbow'?'#ec4899':col;el.innerHTML='<img src="'+b.img+'" alt="'+b.name+'" loading="lazy"><div class="bn">'+b.name+'</div><div class="br" style="color:'+(col==='rainbow'?'#ec4899':col)+'">'+b.rarity+'</div><div class="bq">x'+d.inventory[n]+'</div>';g.appendChild(el)})}
function fillSelects(){const d=getData(currentUser());const opts=Object.keys(d.inventory).filter(n=>d.inventory[n]>0).map(n=>'<option value="'+n.replace(/"/g,'"')+'">'+n+' x'+d.inventory[n]+'</option>').join('')||'<option value="">No blooks</option>';['bazaarSelect','tradeBlook','giftBlook'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML=opts})}
function listOnBazaar(){const name=document.getElementById('bazaarSelect').value;const price=+document.getElementById('bazaarPrice').value;if(!name||!price)return;const u=currentUser();const d=getData(u);if(!d.inventory[name])return;d.inventory[name]--;if(!d.inventory[name])delete d.inventory[name];saveData(u,d);const list=getGlobal('bazaar',[]);list.push({id:Date.now()+Math.random(),seller:u,blook:name,price});setGlobal('bazaar',list);refreshUI()}
function renderBazaar(){const list=getGlobal('bazaar',[]);const el=document.getElementById('bazaarList');el.innerHTML='';if(!list.length){el.innerHTML='<p class="muted">No listings.</p>';return}list.forEach(item=>{const b=blookByName[item.blook];const row=document.createElement('div');row.className='row';row.innerHTML='<div style="display:flex;align-items:center;gap:10px">'+(b?'<img src="'+b.img+'" width="40" height="40">':'')+'<div><b>'+item.blook+'</b><div class="muted" style="font-size:.8rem">'+item.seller+'</div></div></div><div style="display:flex;gap:8px;align-items:center"><span>'+item.price+' tokens</span><button class="btn sm" onclick="buyBazaar(\''+item.id+'\')">Buy</button></div>';el.appendChild(row)})}
function buyBazaar(id){const list=getGlobal('bazaar',[]);const idx=list.findIndex(x=>String(x.id)===String(id));if(idx<0)return;const item=list[idx];const u=currentUser();if(item.seller===u)return;const d=getData(u);if(d.tokens<item.price){alert('Not enough tokens');return}d.tokens-=item.price;d.inventory[item.blook]=(d.inventory[item.blook]||0)+1;saveData(u,d);const s=getData(item.seller);s.tokens+=item.price;saveData(item.seller,s);list.splice(idx,1);setGlobal('bazaar',list);refreshUI()}
function renderCraft(){const d=getData(currentUser());const el=document.getElementById('craftList');el.innerHTML='';const groups={};Object.keys(d.inventory).forEach(n=>{const b=blookByName[n];if(!b||d.inventory[n]<5)return;if(['Uncommon','Rare'].includes(b.rarity))groups[n]=d.inventory[n]});const keys=Object.keys(groups);if(!keys.length){el.innerHTML='<p class="muted">Need 5 of the same Uncommon or Rare blook.</p>';return}keys.forEach(n=>{const b=blookByName[n];const row=document.createElement('div');row.className='row';row.innerHTML='<div style="display:flex;align-items:center;gap:10px"><img src="'+b.img+'" width="40" height="40"><span>5x '+n+' from '+b.pack+'</span></div><button class="btn sm" onclick="doCraft(\''+n.replace(/'/g,"\\'")+'\')">Craft</button>';el.appendChild(row)})}
function doCraft(name){const u=currentUser();const d=getData(u);const b=blookByName[name];if(!b||(d.inventory[name]||0)<5)return;d.inventory[name]-=5;if(!d.inventory[name])delete d.inventory[name];const pack=PACKS.find(p=>p.name===b.pack);let got=null;if(pack){const entries=pack.blooks.map(n=>blookByName[n]).filter(x=>x&&x.chance<b.chance&&x.chance>0);if(entries.length){const total=entries.reduce((s,x)=>s+x.chance,0);let roll=Math.random()*total;for(const e of entries){roll-=e.chance;if(roll<=0){got=e;break}}if(!got)got=entries[entries.length-1]}else got=rollPack(b.pack)}if(got){d.inventory[got.name]=(d.inventory[got.name]||0)+1;d.exp+=(RARITIES[got.rarity]?.exp||0)}saveData(u,d);if(got){document.getElementById('openImg').src=got.img;document.getElementById('openName').textContent=got.name;document.getElementById('openRarity').textContent=got.rarity;document.getElementById('openModal').classList.add('active')}refreshUI()}
function sendTrade(){const to=document.getElementById('tradeUser').value.trim();const bid=document.getElementById('tradeBlook').value;const tok=+document.getElementById('tradeTokens').value||0;const u=currentUser();if(!to||to===u||!getUsers()[to]){alert('Invalid user');return}const d=getData(u);if(bid&&!d.inventory[bid])return;if(d.tokens<tok)return;if(bid){d.inventory[bid]--;if(!d.inventory[bid])delete d.inventory[bid]}d.tokens-=tok;saveData(u,d);const trades=getGlobal('trades',[]);trades.push({id:Date.now()+Math.random(),from:u,to,blook:bid||null,tokens:tok});setGlobal('trades',trades);refreshUI()}
function renderTrade(){const u=currentUser();const trades=getGlobal('trades',[]).filter(t=>t.to===u);const el=document.getElementById('tradeList');el.innerHTML='';if(!trades.length){el.innerHTML='<p class="muted">No incoming trades.</p>';return}trades.forEach(t=>{const row=document.createElement('div');row.className='row';row.innerHTML='<span>From <b>'+t.from+'</b>: '+(t.blook||'—')+' + '+t.tokens+' tokens</span><span><button class="btn sm" onclick="acceptTrade(\''+t.id+'\')">Accept</button> <button class="btn sm ghost" onclick="declineTrade(\''+t.id+'\')">Decline</button></span>';el.appendChild(row)})}
function acceptTrade(id){const trades=getGlobal('trades',[]);const idx=trades.findIndex(t=>String(t.id)===String(id));if(idx<0)return;const t=trades[idx];const d=getData(currentUser());if(t.blook)d.inventory[t.blook]=(d.inventory[t.blook]||0)+1;d.tokens+=t.tokens;saveData(currentUser(),d);trades.splice(idx,1);setGlobal('trades',trades);refreshUI()}
function declineTrade(id){const trades=getGlobal('trades',[]);const idx=trades.findIndex(t=>String(t.id)===String(id));if(idx<0)return;const t=trades[idx];const from=getData(t.from);if(t.blook)from.inventory[t.blook]=(from.inventory[t.blook]||0)+1;from.tokens+=t.tokens;saveData(t.from,from);trades.splice(idx,1);setGlobal('trades',trades);refreshUI()}
function createClan(){const name=document.getElementById('clanName').value.trim();if(!name)return;const u=currentUser();const d=getData(u);d.clan=name;saveData(u,d);const clans=getGlobal('clans',{});if(!clans[name])clans[name]=[];if(!clans[name].includes(u))clans[name].push(u);setGlobal('clans',clans);refreshUI()}
function leaveClan(){const u=currentUser();const d=getData(u);const n=d.clan;d.clan='';saveData(u,d);const clans=getGlobal('clans',{});if(n&&clans[n]){clans[n]=clans[n].filter(x=>x!==u);setGlobal('clans',clans)}refreshUI()}
function renderClans(){const d=getData(currentUser());document.getElementById('clanStatus').textContent=d.clan?('In clan: '+d.clan):'Not in a clan.';const clans=getGlobal('clans',{});const el=document.getElementById('clanList');el.innerHTML=Object.keys(clans).map(n=>'<div class="row"><b>'+n+'</b><span class="muted">'+clans[n].length+' members</span></div>').join('')||'<p class="muted">No clans.</p>'}
function addFriend(){const name=document.getElementById('friendName').value.trim();const u=currentUser();if(!name||!getUsers()[name]||name===u)return;const d=getData(u);if(!d.friends.includes(name))d.friends.push(name);saveData(u,d);refreshUI()}
function renderFriends(){const d=getData(currentUser());const el=document.getElementById('friendsList');el.innerHTML=d.friends.map(f=>'<div class="row"><span>'+f+'</span><button class="btn sm ghost" onclick="removeFriend(\''+f+'\')">Remove</button></div>').join('')||'<p class="muted">No friends.</p>'}
function removeFriend(f){const d=getData(currentUser());d.friends=d.friends.filter(x=>x!==f);saveData(currentUser(),d);refreshUI()}
function sendChat(){const input=document.getElementById('chatInput');const text=input.value.trim();if(!text)return;const chat=getGlobal('chat',[]);chat.push({user:currentUser(),text});if(chat.length>80)chat.shift();setGlobal('chat',chat);input.value='';renderChat()}
function renderChat(){const el=document.getElementById('chatLog');el.innerHTML=getGlobal('chat',[]).slice(-40).map(m=>'<div class="chat-line"><b>'+m.user+'</b>: '+String(m.text).replace(/</g,'<')+'</div>').join('');el.scrollTop=el.scrollHeight}
function renderLB(){const rows=Object.keys(getUsers()).map(u=>{const d=getData(u);return{u,tokens:d.tokens,b:Object.values(d.inventory).reduce((a,c)=>a+c,0)}}).sort((a,b)=>b.tokens-a.tokens);document.getElementById('lbList').innerHTML=rows.map((r,i)=>'<div class="row"><span>#'+(i+1)+' <b>'+r.u+'</b></span><span>'+r.tokens.toLocaleString()+' tokens · '+r.b+' blooks</span></div>').join('')||'<p class="muted">Empty</p>'}
function sendGift(){const to=document.getElementById('giftUser').value.trim();const bid=document.getElementById('giftBlook').value;const u=currentUser();if(!to||!bid||!getUsers()[to])return;const d=getData(u);if(!d.inventory[bid])return;d.inventory[bid]--;if(!d.inventory[bid])delete d.inventory[bid];saveData(u,d);const gifts=getGlobal('gifts',[]);gifts.push({id:Date.now()+Math.random(),from:u,to,blook:bid});setGlobal('gifts',gifts);refreshUI()}
function renderGifts(){const u=currentUser();const gifts=getGlobal('gifts',[]).filter(g=>g.to===u);const el=document.getElementById('giftList');el.innerHTML=gifts.map(g=>'<div class="row"><span>From '+g.from+': '+g.blook+'</span><button class="btn sm" onclick="claimGift(\''+g.id+'\')">Claim</button></div>').join('')||'<p class="muted">No gifts.</p>'}
function claimGift(id){const gifts=getGlobal('gifts',[]);const idx=gifts.findIndex(g=>String(g.id)===String(id));if(idx<0)return;const g=gifts[idx];const d=getData(currentUser());d.inventory[g.blook]=(d.inventory[g.blook]||0)+1;saveData(currentUser(),d);gifts.splice(idx,1);setGlobal('gifts',gifts);refreshUI()}
function doMine(){const u=currentUser();const d=getData(u);const now=Date.now();if(now-d.lastMine<2500){document.getElementById('mineStatus').textContent='Cooldown...';return}d.lastMine=now;d.mined++;const gain=Math.floor(Math.random()*20)+10;d.tokens+=gain;saveData(u,d);document.getElementById('mineResult').textContent='+'+gain+' tokens';refreshUI()}
function claimDaily(){const u=currentUser();const d=getData(u);const day=new Date().toDateString();if(d.lastClaim===day){alert('Already claimed today');return}d.lastClaim=day;d.tokens+=CATALOG.claimAmount;saveData(u,d);alert('+'+CATALOG.claimAmount+' tokens');refreshUI()}
function adminGive(){const me=getData(currentUser());if(!['admin','coowner','owner'].includes(me.role))return;const t=document.getElementById('adminUser').value.trim();const amt=+document.getElementById('adminAmt').value;if(!getUsers()[t]||!amt)return;const d=getData(t);d.tokens+=amt;saveData(t,d);document.getElementById('adminMsg').textContent='Done';refreshUI()}
function adminRole(){const me=getData(currentUser());if(!['owner','coowner'].includes(me.role))return;const t=document.getElementById('adminRoleUser').value.trim();const role=document.getElementById('adminRole').value;if(!getUsers()[t])return;const d=getData(t);d.role=role;saveData(t,d);document.getElementById('adminMsg').textContent=t+' -> '+role;buildNav();refreshUI()}
function changeUsername(){const oldN=currentUser(),name=document.getElementById('newUsername').value.trim(),pass=document.getElementById('userPass').value;const users=getUsers();if(!users[oldN]||users[oldN]!==pass||!name||users[name]){document.getElementById('userMsg').textContent='Failed';return}users[name]=users[oldN];delete users[oldN];const data=safeGet('ck_data_'+oldN,'');if(data){safeSet('ck_data_'+name,data);try{localStorage.removeItem('ck_data_'+oldN)}catch(e){}}safeSet('ck_users',JSON.stringify(users));safeSet('ck_current',name);safeSet('ck_last',name);document.getElementById('userMsg').textContent='Updated';document.getElementById('userMsg').style.color='#4ade80';refreshUI()}
function changePassword(){const n=currentUser(),o=document.getElementById('oldPass').value,p=document.getElementById('newPass').value,p2=document.getElementById('newPass2').value;const users=getUsers();if(!users[n]||users[n]!==o||p!==p2||p.length<3){document.getElementById('passMsg').textContent='Failed';return}users[n]=p;safeSet('ck_users',JSON.stringify(users));document.getElementById('passMsg').textContent='Updated';document.getElementById('passMsg').style.color='#4ade80'}
function deleteAccount(){const n=currentUser(),p=document.getElementById('delPass').value;const users=getUsers();if(!users[n]||users[n]!==p)return;if(!confirm('Delete forever?'))return;delete users[n];safeSet('ck_users',JSON.stringify(users));try{localStorage.removeItem('ck_data_'+n);localStorage.removeItem('ck_current')}catch(e){}location.reload()}
